name: tooly
description: Tooly is a package based in Lodash for Dart that contain utilities for working with lists, maps, sets and objects.
version: 0.7.1
repository: https://github.com/andygeek/tooly
homepage: https://andygeek.github.io/tooly-website/

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
